$fileName = "build.txt"
"BUILD VERSION: $env:APPVEYOR_BUILD_VERSION" >> $fileName
"COMMIT SHA: $env:APPVEYOR_REPO_COMMIT" >> $fileName
"COMMIT TIMESTAMP: $env:APPVEYOR_REPO_COMMIT_TIMESTAMP" >> $fileName
"COMMIT MESSAGE: $env:APPVEYOR_REPO_COMMIT_MESSAGE" >> $fileName
"COMMIT AUTHOR: $env:APPVEYOR_REPO_COMMIT_AUTHOR" >> $fileName
"COMMIT AUTHOR EMAIL: $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL" >> $fileName